# Generated by Django 2.2.11 on 2020-03-18 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiketing', '0002_cinema'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sanse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('price', models.IntegerField()),
                ('salable_seats', models.IntegerField()),
                ('free_seat', models.IntegerField()),
                ('status', models.IntegerField(choices=[(1, 'فروش آغاز نشده'), (2, 'در حال بلیت فروشی'), (3, 'بلیت تمام شد'), (4, 'پایان فروش'), (5, 'فیلم پخش شد'), (6, 'نمایش لغو شد')])),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tiketing.Cinema')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tiketing.Movie')),
            ],
        ),
    ]
