# Generated by Django 2.2.11 on 2020-03-19 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiketing', '0003_sanse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cinema',
            options={'verbose_name': 'سینما', 'verbose_name_plural': 'سینما'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': 'فیلم', 'verbose_name_plural': 'فیلم'},
        ),
        migrations.AlterModelOptions(
            name='sanse',
            options={'verbose_name': 'سانس', 'verbose_name_plural': 'سانس'},
        ),
        migrations.AddField(
            model_name='cinema',
            name='image',
            field=models.ImageField(default='temporary', upload_to='cinema_image/', verbose_name='تصویر'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.ImageField(default='tempp', upload_to='movie_poster/', verbose_name='پوستر'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cinema',
            name='address',
            field=models.TextField(verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='capacity',
            field=models.IntegerField(verbose_name='ظرفیت'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='cinema_code',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='کد سینما'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='city',
            field=models.CharField(default='تهران', max_length=30, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='name',
            field=models.CharField(max_length=50, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='phone',
            field=models.CharField(max_length=20, null=True, verbose_name='تلفن'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='descreption',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.CharField(max_length=50, verbose_name='کارگردان'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='length',
            field=models.IntegerField(verbose_name='زمان فیلم'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.IntegerField(verbose_name='سال تولید'),
        ),
        migrations.AlterField(
            model_name='sanse',
            name='cinema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tiketing.Cinema', verbose_name='سینما'),
        ),
        migrations.AlterField(
            model_name='sanse',
            name='free_seat',
            field=models.IntegerField(verbose_name='صندلی های خالی'),
        ),
        migrations.AlterField(
            model_name='sanse',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tiketing.Movie', verbose_name='فیلم'),
        ),
        migrations.AlterField(
            model_name='sanse',
            name='price',
            field=models.IntegerField(verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='sanse',
            name='salable_seats',
            field=models.IntegerField(verbose_name='صندلی های قابل فروش'),
        ),
        migrations.AlterField(
            model_name='sanse',
            name='start_time',
            field=models.DateTimeField(verbose_name='زمان شروع'),
        ),
        migrations.AlterField(
            model_name='sanse',
            name='status',
            field=models.IntegerField(choices=[(1, 'فروش آغاز نشده'), (2, 'در حال بلیت فروشی'), (3, 'بلیت تمام شد'), (4, 'پایان فروش'), (5, 'فیلم پخش شد'), (6, 'نمایش لغو شد')], verbose_name='وضعیت'),
        ),
    ]
